fix dispatcher
using Dispatcher.Default caused an issue when injected.
Therefore, switching to Dispatcher.Main.

Error message if using Dispatcher.Default:
```
2022-12-01 19:01:22.959 8557-8582/com.smaillimp.yatzy E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.smaillimp.yatzy, PID: 8557
    java.lang.IllegalStateException: Reading a state that was created after the snapshot was taken or in a snapshot that has not yet been applied
```